language: python
python:
 - "3.5"

services:
 - redis-server
 - mysql

before install:
 - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('4236') where User='root';"
 - sudo mysql_upgrade
 - sudo service mysql restart

install:
 - pip3 install -r requirements.txt

script:
 - pytest --ignore="API_DOC/" --ignore="Reporter/tests/test_reporter.py"
