language: python
python:
 - "3.5"

services:
 - redis-server
 - mysql

install:
 - pip3 install -r requirements.txt

before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('4236') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

script:
 - pytest --ignore=API_DOC/ --ignore=Reporter/
