language: python
python:
 - "3.5"

services:
 - redis-server
 - mysql

install:
 - pip3 install -r requirements.txt
 - mysql_upgrade -u root -p --force
 - systemctl restart mysqld
 
script:
 - pytest --ignore=API_DOC/
