version: '3.7'

services:
  fetcher:
    build:
      context: .
      dockerfile: Dockerfiles/Fetcher.Dockerfile
    networks:
      tweet-master:
        aliases:
         - fetcher

  redis:
    image: redis:5-alpine
    networks:
      tweet-master:
        aliases:
         - redisfetcher

  rsyslog:
    build:
      context: .
      dockerfile: Dockerfiles/Rsyslog.Dockerfile
    networks:
      tweet-master:
        aliases:
         - rsyslog
   
  mysql:
    image: mysql:8
    networks:
      tweet-master:
        aliases:
         - localhost
  
  rabbitmq:
    image: rabbitmq:3-alpine
    networks:
      tweet-master:
        aliases:
         - rabbitTweetMaster

networks:
  tweet-master:
    external: false
