version: '3.3'

services:
  fetcher:
    build:
      context: .
      dockerfile: Dockerfiles/Fetcher.Dockerfile
    networks:
      tweet-master:
        aliases:
         - fetcher

  mysql:
    image: mysql:8
    networks:
      tweet-master:
        aliases:
         - mysqlTweetMaster
    environment:
      MYSQL_ROOT_PASSWORD: "4236"

  campaign_api:
    build:
      context: .
      dockerfile: Dockerfiles/Campaign_api.Dockerfile
    networks:
      tweet-master:
        aliases:
         - campaign_api
    ports:
      - 5000:5000

  redis:
    image: redis:5-alpine
    networks:acdc
      tweet-master:
        aliases:
         - redisfetcher

  rsyslog:
    build:
      context: .
      dockerfile: Dockerfiles/Rsyslog.Dockerfile
    networks:
      tweet-master:
        aliases:
         - rsyslog

networks:
  tweet-master:
    external: true
