# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Campaign(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, start_date: datetime=None, end_date: datetime=None, email: str=None, mentions: List[str]=None, hashtags: List[str]=None):  # noqa: E501
        """Campaign - a model defined in Swagger

        :param start_date: The start_date of this Campaign.  # noqa: E501
        :type start_date: datetime
        :param end_date: The end_date of this Campaign.  # noqa: E501
        :type end_date: datetime
        :param email: The email of this Campaign.  # noqa: E501
        :type email: str
        :param mentions: The mentions of this Campaign.  # noqa: E501
        :type mentions: List[str]
        :param hashtags: The hashtags of this Campaign.  # noqa: E501
        :type hashtags: List[str]
        """
        self.swagger_types = {
            'start_date': datetime,
            'end_date': datetime,
            'email': str,
            'mentions': List[str],
            'hashtags': List[str]
        }

        self.attribute_map = {
            'start_date': 'startDate',
            'end_date': 'endDate',
            'email': 'email',
            'mentions': 'mentions',
            'hashtags': 'hashtags'
        }

        self._start_date = start_date
        self._end_date = end_date
        self._email = email
        self._mentions = mentions
        self._hashtags = hashtags

    @classmethod
    def from_dict(cls, dikt) -> 'Campaign':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Campaign of this Campaign.  # noqa: E501
        :rtype: Campaign
        """
        return util.deserialize_model(dikt, cls)

    @property
    def start_date(self) -> datetime:
        """Gets the start_date of this Campaign.


        :return: The start_date of this Campaign.
        :rtype: datetime
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date: datetime):
        """Sets the start_date of this Campaign.


        :param start_date: The start_date of this Campaign.
        :type start_date: datetime
        """

        self._start_date = start_date

    @property
    def end_date(self) -> datetime:
        """Gets the end_date of this Campaign.


        :return: The end_date of this Campaign.
        :rtype: datetime
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date: datetime):
        """Sets the end_date of this Campaign.


        :param end_date: The end_date of this Campaign.
        :type end_date: datetime
        """

        self._end_date = end_date

    @property
    def email(self) -> str:
        """Gets the email of this Campaign.


        :return: The email of this Campaign.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this Campaign.


        :param email: The email of this Campaign.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def mentions(self) -> List[str]:
        """Gets the mentions of this Campaign.


        :return: The mentions of this Campaign.
        :rtype: List[str]
        """
        return self._mentions

    @mentions.setter
    def mentions(self, mentions: List[str]):
        """Sets the mentions of this Campaign.


        :param mentions: The mentions of this Campaign.
        :type mentions: List[str]
        """
        if mentions is None:
            raise ValueError("Invalid value for `mentions`, must not be `None`")  # noqa: E501

        self._mentions = mentions

    @property
    def hashtags(self) -> List[str]:
        """Gets the hashtags of this Campaign.


        :return: The hashtags of this Campaign.
        :rtype: List[str]
        """
        return self._hashtags

    @hashtags.setter
    def hashtags(self, hashtags: List[str]):
        """Sets the hashtags of this Campaign.


        :param hashtags: The hashtags of this Campaign.
        :type hashtags: List[str]
        """
        if hashtags is None:
            raise ValueError("Invalid value for `hashtags`, must not be `None`")  # noqa: E501

        self._hashtags = hashtags
