# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Tweet(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id_t: int=None, fecha_inicio: datetime=None, fecha_fin: datetime=None, mentions: List[str]=None, hashtags: List[str]=None):  # noqa: E501
        """Tweet - a model defined in Swagger

        :param id_t: The id_t of this Tweet.  # noqa: E501
        :type id_t: int
        :param fecha_inicio: The fecha_inicio of this Tweet.  # noqa: E501
        :type fecha_inicio: datetime
        :param fecha_fin: The fecha_fin of this Tweet.  # noqa: E501
        :type fecha_fin: datetime
        :param mentions: The mentions of this Tweet.  # noqa: E501
        :type mentions: List[str]
        :param hashtags: The hashtags of this Tweet.  # noqa: E501
        :type hashtags: List[str]
        """
        self.swagger_types = {
            'id_t': int,
            'fecha_inicio': datetime,
            'fecha_fin': datetime,
            'mentions': List[str],
            'hashtags': List[str]
        }

        self.attribute_map = {
            'id_t': 'idT',
            'fecha_inicio': 'fechaInicio',
            'fecha_fin': 'fechaFin',
            'mentions': 'mentions',
            'hashtags': 'hashtags'
        }

        self._id_t = id_t
        self._fecha_inicio = fecha_inicio
        self._fecha_fin = fecha_fin
        self._mentions = mentions
        self._hashtags = hashtags

    @classmethod
    def from_dict(cls, dikt) -> 'Tweet':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Tweet of this Tweet.  # noqa: E501
        :rtype: Tweet
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_t(self) -> int:
        """Gets the id_t of this Tweet.


        :return: The id_t of this Tweet.
        :rtype: int
        """
        return self._id_t

    @id_t.setter
    def id_t(self, id_t: int):
        """Sets the id_t of this Tweet.


        :param id_t: The id_t of this Tweet.
        :type id_t: int
        """
        if id_t is None:
            raise ValueError("Invalid value for `id_t`, must not be `None`")  # noqa: E501

        self._id_t = id_t

    @property
    def fecha_inicio(self) -> datetime:
        """Gets the fecha_inicio of this Tweet.


        :return: The fecha_inicio of this Tweet.
        :rtype: datetime
        """
        return self._fecha_inicio

    @fecha_inicio.setter
    def fecha_inicio(self, fecha_inicio: datetime):
        """Sets the fecha_inicio of this Tweet.


        :param fecha_inicio: The fecha_inicio of this Tweet.
        :type fecha_inicio: datetime
        """
        if fecha_inicio is None:
            raise ValueError("Invalid value for `fecha_inicio`, must not be `None`")  # noqa: E501

        self._fecha_inicio = fecha_inicio

    @property
    def fecha_fin(self) -> datetime:
        """Gets the fecha_fin of this Tweet.


        :return: The fecha_fin of this Tweet.
        :rtype: datetime
        """
        return self._fecha_fin

    @fecha_fin.setter
    def fecha_fin(self, fecha_fin: datetime):
        """Sets the fecha_fin of this Tweet.


        :param fecha_fin: The fecha_fin of this Tweet.
        :type fecha_fin: datetime
        """
        if fecha_fin is None:
            raise ValueError("Invalid value for `fecha_fin`, must not be `None`")  # noqa: E501

        self._fecha_fin = fecha_fin

    @property
    def mentions(self) -> List[str]:
        """Gets the mentions of this Tweet.


        :return: The mentions of this Tweet.
        :rtype: List[str]
        """
        return self._mentions

    @mentions.setter
    def mentions(self, mentions: List[str]):
        """Sets the mentions of this Tweet.


        :param mentions: The mentions of this Tweet.
        :type mentions: List[str]
        """
        if mentions is None:
            raise ValueError("Invalid value for `mentions`, must not be `None`")  # noqa: E501

        self._mentions = mentions

    @property
    def hashtags(self) -> List[str]:
        """Gets the hashtags of this Tweet.


        :return: The hashtags of this Tweet.
        :rtype: List[str]
        """
        return self._hashtags

    @hashtags.setter
    def hashtags(self, hashtags: List[str]):
        """Sets the hashtags of this Tweet.


        :param hashtags: The hashtags of this Tweet.
        :type hashtags: List[str]
        """
        if hashtags is None:
            raise ValueError("Invalid value for `hashtags`, must not be `None`")  # noqa: E501

        self._hashtags = hashtags
